---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by HKex.
--- DateTime: 2025/8/5 14:43
---

--库存不足返回1，已下单返回2，正常返回0

local voucherId = ARGV[1]

local userId = ARGV[2]

local orderId = ARGV[3]

--库存和订单key
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

--判断库存是否充足
if(tonumber(redis.call('get',stockKey)) <= 0)then
    --库存不足返回1
    return 1
end

--判断用户是否重复下单
if(tonumber(redis.call('sismember',orderKey, userId)) == 1)then
    --重复下单返回2
    return 2
end

--扣库存
redis.call('incrby',stockKey, -1)
--添加订单
redis.call('sadd',orderKey, userId)

return 0